permalink: /:title/

url:
baseurl:

highlighter: rouge

sass:
  sass_dir: public/css
  style: :compressed
  
gems:
  - jekyll-redirect-from #https://help.github.com/articles/redirects-on-github-pages
  
social:
  email: mailto:contact@programminglife.io
  github: http://github.com/andreivisan
  linkedin: https://www.linkedin.com/company-beta/17906021/
  facebook: https://www.facebook.com/programminglife.io
  twitter: https://twitter.com/ProgrammingIife
  instagram: https://www.instagram.com/programminglife.io/
  stackoverflow: http://stackoverflow.com/users/3426717/andrei
  googleplus: https://plus.google.com/115682876566536754762
  instagram: https://www.instagram.com/programminglife.io/
